from __future__ import annotations

import io
import re
from datetime import datetime
from typing import Any

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from modal_ml.utils import supabase_client, update_job_progress, upload_to_storage

VIOLET = colors.HexColor("#a78bfa")
CYAN = colors.HexColor("#06b6d4")
DARK = colors.HexColor("#05030f")
GREEN = colors.HexColor("#22c55e")
RED = colors.HexColor("#ef4444")

SPECIAL_CATEGORY_PATTERN = re.compile(r"health|religion|political|faith|diagnosis|medical", re.IGNORECASE)
PHI_PATTERN = re.compile(
    r"name|address|date|phone|fax|email|ssn|social|mrn|health|account|certificate|license|vin|vehicle|device|url|ip|biometric|photo",
    re.IGNORECASE,
)
PHI_ENTITIES = {"PERSON", "US_SSN", "PHONE_NUMBER", "EMAIL_ADDRESS", "IP_ADDRESS"}


def _draw_footer(pdf: canvas.Canvas) -> None:
    footer = "Generated by Syntho · syntho.vercel.app · For informational purposes only · Not legal advice"
    pdf.setFont("Helvetica", 8)
    pdf.setFillColor(colors.HexColor("#6b7280"))
    pdf.drawCentredString(A4[0] / 2, 10 * mm, footer)


def _draw_header(pdf: canvas.Canvas, title: str) -> None:
    pdf.setFillColor(DARK)
    pdf.rect(0, A4[1] - 28 * mm, A4[0], 28 * mm, fill=1, stroke=0)
    pdf.setFillColor(VIOLET)
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(16 * mm, A4[1] - 17 * mm, title)


def _draw_checks(pdf: canvas.Canvas, checks: list[dict[str, Any]], y_start: float) -> None:
    y = y_start
    for check in checks:
        if y < 30 * mm:
            _draw_footer(pdf)
            pdf.showPage()
            _draw_header(pdf, "Compliance Checks")
            y = A4[1] - 38 * mm
        mark = "✓" if check["passed"] else "✗"
        color = GREEN if check["passed"] else RED
        pdf.setFillColor(color)
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(16 * mm, y, mark)
        pdf.setFillColor(colors.black)
        pdf.setFont("Helvetica-Bold", 10)
        pdf.drawString(24 * mm, y, check["name"])
        y -= 5 * mm
        pdf.setFont("Helvetica", 9)
        pdf.drawString(24 * mm, y, check["explanation"][:110])
        y -= 8 * mm


def _contains_special_categories(df: pd.DataFrame) -> bool:
    for col in df.columns:
        if SPECIAL_CATEGORY_PATTERN.search(col):
            return True
        sample = df[col].dropna().astype(str).head(20)
        if sample.str.contains(SPECIAL_CATEGORY_PATTERN, na=False).any():
            return True
    return False


def _detect_phi_columns(df: pd.DataFrame) -> list[str]:
    flagged = []
    for col in df.columns:
        if PHI_PATTERN.search(col):
            flagged.append(col)
            continue
        sample = df[col].dropna().astype(str).head(30)
        if sample.str.contains(PHI_PATTERN, na=False).any():
            flagged.append(col)
    return flagged


def generate_compliance_report(
    original_df: pd.DataFrame,
    synthetic_df: pd.DataFrame,
    privacy_result: dict[str, Any],
    synthetic_dataset_id: str,
    dataset_name: str,
) -> tuple[bytes, dict[str, Any]]:
    privacy_score = float(privacy_result.get("overall_score", 0) or 0)
    pii_detected = privacy_result.get("pii_detected", {}) or {}
    overlap_pct = float(privacy_result.get("details", {}).get("overlap_pct", 0) or 0)

    direct_identifier_found = len(pii_detected) > 0
    no_direct_identifiers = not direct_identifier_found
    no_quasi_identifiers = privacy_score > 60
    data_minimization = synthetic_df.shape[1] <= original_df.shape[1]
    no_special_categories = not _contains_special_categories(synthetic_df)
    cannot_be_traced = overlap_pct < 0.05

    gdpr_checks = [
        {"name": "no_direct_identifiers", "passed": no_direct_identifiers, "explanation": "No direct identifiers detected by Presidio." if no_direct_identifiers else "Direct identifier signals detected in synthetic data."},
        {"name": "no_quasi_identifiers", "passed": no_quasi_identifiers, "explanation": f"Privacy score is {privacy_score:.1f}; must be > 60."},
        {"name": "data_minimization", "passed": data_minimization, "explanation": "Synthetic column count is less than or equal to original." if data_minimization else "Synthetic dataset includes extra columns."},
        {"name": "no_special_categories", "passed": no_special_categories, "explanation": "No health/religion/political indicators detected." if no_special_categories else "Potential special-category data indicators found."},
        {"name": "cannot_be_traced", "passed": cannot_be_traced, "explanation": f"Row overlap is {overlap_pct:.2%}; must be < 5%."},
    ]

    phi_columns = _detect_phi_columns(synthetic_df)
    pii_entities = {e for col in pii_detected.values() for e in col.get("entities", [])}
    no_phi = privacy_score > 70 and len(pii_entities.intersection(PHI_ENTITIES)) == 0
    safe_harbor_applied = len(phi_columns) == 0
    deidentification_verified = privacy_score > 70

    hipaa_checks = [
        {"name": "no_phi", "passed": no_phi, "explanation": "No PHI entities detected and privacy score > 70." if no_phi else "PHI entities detected or privacy score too low."},
        {"name": "safe_harbor_applied", "passed": safe_harbor_applied, "explanation": "No Safe Harbor identifier patterns found." if safe_harbor_applied else "Potential Safe Harbor identifiers found."},
        {"name": "deidentification_verified", "passed": deidentification_verified, "explanation": f"Privacy score is {privacy_score:.1f}; must be > 70."},
    ]

    gdpr_passed = all(c["passed"] for c in gdpr_checks)
    hipaa_passed = all(c["passed"] for c in hipaa_checks)
    passed = gdpr_passed and hipaa_passed

    findings = {
        "gdpr_checks": gdpr_checks,
        "hipaa_checks": hipaa_checks,
        "privacy_score": privacy_score,
        "overlap_pct": overlap_pct,
        "phi_columns": phi_columns,
    }

    recommendations = []
    if not passed:
        recommendations = [
            "Remove detected direct identifiers and regenerate synthetic data.",
            "Reduce quasi-identifier uniqueness (bucket dates, round values, group categories).",
            "Apply stronger de-identification to lower overlap below 5%.",
        ]

    pdf_bytes_io = io.BytesIO()
    pdf = canvas.Canvas(pdf_bytes_io, pagesize=A4)

    # Page 1: Cover
    _draw_header(pdf, "Synthetic Data Compliance Report")
    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica", 11)
    pdf.drawString(16 * mm, A4[1] - 40 * mm, f"Dataset: {dataset_name}")
    pdf.drawString(16 * mm, A4[1] - 48 * mm, f"Synthetic ID: {synthetic_dataset_id}")
    pdf.drawString(16 * mm, A4[1] - 56 * mm, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    pdf.setFillColor(GREEN if passed else RED)
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(16 * mm, A4[1] - 74 * mm, f"VERDICT: {'PASSED' if passed else 'FAILED'}")
    _draw_footer(pdf)
    pdf.showPage()

    # Page 2: Executive summary
    _draw_header(pdf, "Executive Summary")
    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(16 * mm, A4[1] - 42 * mm, f"Privacy Score: {privacy_score:.1f}")
    pdf.drawString(16 * mm, A4[1] - 50 * mm, f"GDPR: {'PASS' if gdpr_passed else 'FAIL'}")
    pdf.drawString(16 * mm, A4[1] - 58 * mm, f"HIPAA: {'PASS' if hipaa_passed else 'FAIL'}")
    pdf.setFont("Helvetica", 10)
    summary = (
        "This synthetic dataset passed all GDPR checks and HIPAA safe harbor criteria. "
        "It is safe for use in development, testing, and sharing."
        if passed
        else "This synthetic dataset failed one or more GDPR/HIPAA checks. Follow recommendations before sharing."
    )
    pdf.drawString(16 * mm, A4[1] - 72 * mm, summary[:115])
    _draw_footer(pdf)
    pdf.showPage()

    # Page 3: GDPR
    _draw_header(pdf, "GDPR Section")
    _draw_checks(pdf, gdpr_checks, A4[1] - 42 * mm)
    _draw_footer(pdf)
    pdf.showPage()

    # Page 4: HIPAA
    _draw_header(pdf, "HIPAA Section")
    _draw_checks(pdf, hipaa_checks, A4[1] - 42 * mm)
    _draw_footer(pdf)

    if recommendations:
        pdf.showPage()
        _draw_header(pdf, "Recommendations")
        y = A4[1] - 42 * mm
        pdf.setFont("Helvetica", 10)
        pdf.setFillColor(colors.black)
        for idx, rec in enumerate(recommendations, start=1):
            pdf.drawString(16 * mm, y, f"{idx}. {rec}")
            y -= 8 * mm
        _draw_footer(pdf)

    pdf.save()
    pdf_bytes = pdf_bytes_io.getvalue()

    compliance_result = {
        "passed": passed,
        "gdpr_passed": gdpr_passed,
        "hipaa_passed": hipaa_passed,
        "findings": findings,
    }
    return pdf_bytes, compliance_result


def compliance_reporter(
    original_df: pd.DataFrame,
    synthetic_df: pd.DataFrame,
    context: dict[str, Any] | None = None,
) -> dict[str, Any]:
    context = context or {}
    payload = context.get("payload", {})
    synthetic_dataset_id = str(context.get("synthetic_dataset_id") or payload.get("synthetic_dataset_id"))
    dataset_name = str(payload.get("dataset_name") or payload.get("dataset_id") or "Dataset")

    if not synthetic_dataset_id:
        raise ValueError("synthetic_dataset_id is required in context")

    privacy_record = (
        supabase_client()
        .table("privacy_scores")
        .select("*")
        .eq("synthetic_dataset_id", synthetic_dataset_id)
        .order("created_at", desc=True)
        .limit(1)
        .maybe_single()
        .execute()
    )
    privacy_result = privacy_record.data or {}

    pdf_bytes, compliance_result = generate_compliance_report(
        original_df=original_df,
        synthetic_df=synthetic_df,
        privacy_result=privacy_result,
        synthetic_dataset_id=synthetic_dataset_id,
        dataset_name=dataset_name,
    )

    file_path = f"reports/{synthetic_dataset_id}/compliance.pdf"
    upload_to_storage("reports", file_path, pdf_bytes, "application/pdf")

    supabase_client().table("compliance_reports").insert(
        {
            "synthetic_dataset_id": synthetic_dataset_id,
            "report_type": "combined",
            "file_path": file_path,
            "passed": compliance_result["passed"],
            "gdpr_passed": compliance_result["gdpr_passed"],
            "hipaa_passed": compliance_result["hipaa_passed"],
            "findings": compliance_result["findings"],
        }
    ).execute()

    update_job_progress(synthetic_dataset_id, 95, "running", "Compliance report generated")

    return {**compliance_result, "file_path": file_path}
